# Generated by Django 6.0.1 on 2026-02-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rsvp_delete_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
    ]
